package com.example.pranay.fabhotelsassignment.data.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.pranay.fabhotelsassignment.data.db.model.ListPropertyEntity;

import com.example.pranay.fabhotelsassignment.data.db.model.ListPropertyEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig listPropertyEntityDaoConfig;

    private final ListPropertyEntityDao listPropertyEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        listPropertyEntityDaoConfig = daoConfigMap.get(ListPropertyEntityDao.class).clone();
        listPropertyEntityDaoConfig.initIdentityScope(type);

        listPropertyEntityDao = new ListPropertyEntityDao(listPropertyEntityDaoConfig, this);

        registerDao(ListPropertyEntity.class, listPropertyEntityDao);
    }
    
    public void clear() {
        listPropertyEntityDaoConfig.clearIdentityScope();
    }

    public ListPropertyEntityDao getListPropertyEntityDao() {
        return listPropertyEntityDao;
    }

}
